Fine-grained plugins dependendy upload
ManiVaultStudio/ExamplePlugins pull request #32
Opened 2024-09-24 14:09 UTC by alxvth

It is very useful to gather all plugin runtime dependencies in a single folder, immediately after building the plugin.

Here, we gather all runtime dependencies and install them to `${ManiVault_INSTALL_DIR}/$<CONFIGURATION>/PluginDependencies/PLUGINNAME` where the PLUGINNAME is the current plugin's name.

Depends on https://github.com/ManiVaultStudio/core/pull/692 which loads the runtime dependencies automatically before loading the plugin library.

A plugin developer can use `cmake/install_dependencies_utils.cmake` and `cmake/install_dependencies.cmake.in` to set up automatic plugin runtime dependency gathering and installation with these commands:
```cmake
include(cmake/install_dependencies_utils.cmake)
install_dependencies(${PROJECT_NAME} "hwy" "hwy_contrib")
```
We need to pass all targets that we build in our project to `install_dependencies`, which in this example is the plugin itself and two dependencies. Other dependencies that are linked to our plugin `${PROJECT_NAME}` via `find_package` are automatically resolved (given that their respective cmake export files are nicely setup). This even works with dependency chains, as shown in this example, where we link to Faiss, which in turn depends on Lapack and OpenBlas which in turn depends on other libraries.

All installed dependencies are listed like this (current CI output on windows):
```bash
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/blake3.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/faiss.dll
-- Resolved: D:/.conan/bab46b/1/_deps/highway-build/Release/hwy.dll
-- Resolved: D:/.conan/bab46b/1/_deps/highway-build/Release/hwy_contrib.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/libgcc_s_seh-1.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/libgfortran-5.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/liblapack.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/libquadmath-0.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/libwinpthread-1.dll
-- Resolved: D:/.conan/bab46b/1/ExampleDependencies/Release/openblas.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/blake3.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/faiss.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/hwy.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/hwy_contrib.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/libgcc_s_seh-1.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/libgfortran-5.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/liblapack.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/libquadmath-0.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/libwinpthread-1.dll
-- Installing: D:\.conan\bab46b\1\package\Release/PluginDependencies/ExampleDependenciesPlugin/openblas.dll
```

Additionally:
- Show how [vcpkg ](https://github.com/microsoft/vcpkg/) can be used on the CI in combination with conan, see `build.yml` and `conanfile.py`
- Caching vcpkg dependencies on the CI. This requires setting up a secret as shown [here](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages), in our example referred to as `secrets.GH_VCPKG_PACKAGES`
- Set `CMAKE_CXX_STANDARD_REQUIRED` on all platforms, see `conanfile.py`
- Do not set `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` on windows, see `conanfile.py`

2024-10-09 10:52 UTC, alxvth commented
The core now provides `mv_install_dependencies` when using `find_package(ManiVault ... CONFIG)`, i.e. a plugin does not need to define the function in their cmake

2024-10-10 12:19 UTC, ThomasKroes approved these changes

2024-10-11 07:46 UTC, bldrvnlw requested changes
.github/workflows/build.yml: 
Regarding the vcpkg logic : I recommend putting this into a reusable action hosted in the ManiVault/github-actions project. Project specific values can be passed as parameters. I approve this but will add a separate PR for creating this reusable action.

conanfile.py:
Does the manivault_dir needs to be set on self. (line 105)  It is not used outside the generate function. Can this be changed?

2024-10-11 08:03 UTC, alxvth commented
> conanfile.py:
> Does the manivault_dir needs to be set on self. (line 105) It is not used outside the generate function. Can this be changed?

I changed this. It just was that way before but there is no need to bet set to self.

2024-10-11 08:06 UTC, merged